language: java
jdk: oraclejdk9
os: linux
dist: trusty
sudo: false
script: 
-mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
-mvn test -B
services:
- xvfb
cache:
  directories:
  - $HOME/.m2
